import { StickerList } from './sticker_list_class';

export const StickerListData: StickerList[] = [
    {
        'Pernr': '00145166',
        'Request_no': '201001011234',
        'Request_Type': 'R',
        'Sticker_Type': 'Renew',
        'Sticker_Type_Desc': 'Community OutCamp',
        'Sticker_No': '12345678',
        'Expiry_Date': '12/31/9999',
        'sticker_Office': '000006',
        'sticker_Office_Desc': 'DHM',
        'Plate_No_Arabic': '1234ABCD',
        'Plate_No_English': '1234DEFG',
        'Process_Status': '09',
        'Process_Status_Desc': 'Active',
        'veh_Make_Code': '001',
        'veh_Make_Desc': 'Toyota',
        'veh_Model_Code': '501',
        'veh_model_Desc': 'Land Cruiser',
        'Veh_year': '2012'
    },
    {
        'Pernr': '00145166',
        'Request_no': '201001011235',
        'Request_Type': 'R',
        'Sticker_Type': 'Renew',
        'Sticker_Type_Desc': 'Core Area',
        'Sticker_No': '12345679',
        'Expiry_Date': '12/31/9999',
        'sticker_Office': '000006',
        'sticker_Office_Desc': 'DHM',
        'Plate_No_Arabic': '1234ABCD',
        'Plate_No_English': '1234DEFG',
        'Process_Status': '09',
        'Process_Status_Desc': 'Active',
        'veh_Make_Code': '001',
        'veh_Make_Desc': 'Toyota',
        'veh_Model_Code': '501',
        'veh_model_Desc': 'Land Cruiser',
        'Veh_year': '2012'
    },
    {
        'Pernr': '00145166',
        'Request_no': '201001011236',
        'Request_Type': 'R',
        'Sticker_Type': 'Renew',
        'Sticker_Type_Desc': 'Community OutCamp',
        'Sticker_No': '12345680',
        'Expiry_Date': '12/31/9999',
        'sticker_Office': '000007',
        'sticker_Office_Desc': 'DMM',
        'Plate_No_Arabic': '1235ABCD',
        'Plate_No_English': '1235DEFG',
        'Process_Status': '09',
        'Process_Status_Desc': 'Active',
        'veh_Make_Code': '002',
        'veh_Make_Desc': 'Nissan',
        'veh_Model_Code': '602',
        'veh_model_Desc': 'Tida',
        'Veh_year': '2013'
    },
    {
        'Pernr': '00145166',
        'Request_no': '201001011236',
        'Request_Type': 'R',
        'Sticker_Type': 'Renew',
        'Sticker_Type_Desc': 'Arrabiyah',
        'Sticker_No': '12345681',
        'Expiry_Date': '12/31/9999',
        'sticker_Office': '000007',
        'sticker_Office_Desc': 'DMM',
        'Plate_No_Arabic': '1235ABCD',
        'Plate_No_English': '1235DEFG',
        'Process_Status': '09',
        'Process_Status_Desc': 'Active',
        'veh_Make_Code': '002',
        'veh_Make_Desc': 'Nissan',
        'veh_Model_Code': '602',
        'veh_model_Desc': 'Tida',
        'Veh_year': '2013'
    },

    {
        'Pernr': '00145166',
        'Request_no': '201001011234',
        'Request_Type': 'W',
        'Sticker_Type': 'Replacement',
        'Sticker_Type_Desc': 'Community OutCamp',
        'Sticker_No': '12345678',
        'Expiry_Date': '12/31/9999',
        'sticker_Office': '000008',
        'sticker_Office_Desc': 'ABQ',
        'Plate_No_Arabic': '1234ABCD',
        'Plate_No_English': '1234DEFG',
        'Process_Status': '02',
        'Process_Status_Desc': 'Submitted',
        'veh_Make_Code': '001',
        'veh_Make_Desc': 'Toyota',
        'veh_Model_Code': '501',
        'veh_model_Desc': 'Land Cruiser',
        'Veh_year': '2012'
    },
    {
        'Pernr': '00145166',
        'Request_no': '201001011235',
        'Request_Type': 'R',
        'Sticker_Type': 'Renew',
        'Sticker_Type_Desc': 'Core Area',
        'Sticker_No': '12345679',
        'Expiry_Date': '12/31/9999',
        'sticker_Office': '000006',
        'sticker_Office_Desc': 'DHM',
        'Plate_No_Arabic': '1234ABCD',
        'Plate_No_English': '1234DEFG',
        'Process_Status': '03',
        'Process_Status_Desc': 'Approved',
        'veh_Make_Code': '001',
        'veh_Make_Desc': 'Toyota',
        'veh_Model_Code': '501',
        'veh_model_Desc': 'Land Cruiser',
        'Veh_year': '2012'
    },
    {
        'Pernr': '00145166',
        'Request_no': '201001011236',
        'Request_Type': 'R',
        'Sticker_Type': 'Renew',
        'Sticker_Type_Desc': 'Community OutCamp',
        'Sticker_No': '12345680',
        'Expiry_Date': '12/31/9999',
        'sticker_Office': '000007',
        'sticker_Office_Desc': 'DMM',
        'Plate_No_Arabic': '1235ABCD',
        'Plate_No_English': '1235DEFG',
        'Process_Status': '02',
        'Process_Status_Desc': 'Submitted',
        'veh_Make_Code': '002',
        'veh_Make_Desc': 'Nissan',
        'veh_Model_Code': '602',
        'veh_model_Desc': 'Tida',
        'Veh_year': '2013'
    },
    {
        'Pernr': '00145166',
        'Request_no': '201001011236',
        'Request_Type': 'R',
        'Sticker_Type': 'Renew',
        'Sticker_Type_Desc': 'Arrabiyah',
        'Sticker_No': '12345681',
        'Expiry_Date': '12/31/9999',
        'sticker_Office': '000007',
        'sticker_Office_Desc': 'DMM',
        'Plate_No_Arabic': '1235ABCD',
        'Plate_No_English': '1235DEFG',
        'Process_Status': '03',
        'Process_Status_Desc': 'Approved',
        'veh_Make_Code': '002',
        'veh_Make_Desc': 'Nissan',
        'veh_Model_Code': '602',
        'veh_model_Desc': 'Tida',
        'Veh_year': '2013'
    }
    ,
    {
        'Pernr': '00145188',
        'Request_no': '201001011266',
        'Request_Type': 'R',
        'Sticker_Type': 'Renew',
        'Sticker_Type_Desc': 'Arrabiyah',
        'Sticker_No': '12345666',
        'Expiry_Date': '12/31/9999',
        'sticker_Office': '000006',
        'sticker_Office_Desc': 'DMM',
        'Plate_No_Arabic': '1235ABCD',
        'Plate_No_English': '1235DyyFG',
        'Process_Status': '03',
        'Process_Status_Desc': 'Approved',
        'veh_Make_Code': '002',
        'veh_Make_Desc': 'Nissan',
        'veh_Model_Code': '602',
        'veh_model_Desc': 'Tida',
        'Veh_year': '2013'
    }

];